### ISSUE TITLE
Undefined function or variable 'containsMethod'

### ISSUE THREAD

**Issue by irombie** [danyaljj/constrained_clustering#2]
I tried to run the script experiment_toy.m as described in README.md. I got the following error when I did (I am using Matlab R2016b on MacOS):

Undefined function or variable 'containsMethod'.

Error in runClustering (line 102)
if ~containsMethod(name, titles)

Error in experiment_toy (line 22)
runClustering(X,Y,k, 'Gaussian-Mixtures', rate, p, true);

**Comment by Vaisili** [comment]
I meet this problem too

**Comment by se4u** [comment]
I was getting this error too, I grepped through the commit history and it seems that this method was first refd. in commit `8614`. But no other file was added in that commit so maybe Dan just forgot to add this file. In any case, the following does the trick.

```
function ret = containsMethod(e, container)
ret = 0;
if size(container, 1) > 0
    assert(size(container, 1) == 1);
    for i=1:size(container, 2)
        ret = strcmp(container{i}, e);
        if ret == 1
            break
        end
    end
end
```

There were some more path errors after this. See my pr for fixes.

**Comment by danyaljj** [comment]
Thanks @se4u for sending the PR.
